version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/home/node/app/src
        container_name: zipcode-app
        environment:
            PORT: ${PORT}
        expose:
            - '${PORT}'
        ports:
            - '${PORT}:${PORT}'
        command: npm run dev
